# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d066e7592b21ac3b64216d54529015da1eec7a1eeded54f637d032915ae4bc595a603d1f94e9c6db0368e187a2311c860c5792488dca4baef5f4b982ea38331

test:
  secret_key_base: ffad80902ec79d489fe69ce4c2d5ddc7f2475b584b44a782959c60b932acfb1e699e7764f4dee705a2e071cf6c62ed9f4970e94cdda2c7a3390420a892ed3ff1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
